name: ci

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: ci
    runs-on: ubuntu-slim
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: install tools
        uses: jdx/mise-action@9149ea85001c7435d5a66bb127d6a1b6227cb0a5 # v5.0.0
        with:
          cache: false
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: check
        run: pnpm check
      - name: build
        run: pnpm build
      - name: test
        run: pnpm test
